// <auto-generated />
namespace ewide.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddIdcolumnforCoachandCoacheetoCoachingProgramObject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddIdcolumnforCoachandCoacheetoCoachingProgramObject));
        
        string IMigrationMetadata.Id
        {
            get { return "201507180604206_Add Id column for Coach and Coachee to Coaching Program Object"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
