// <auto-generated />
namespace ewide.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class CreateProgramandSession : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateProgramandSession));
        
        string IMigrationMetadata.Id
        {
            get { return "201505050733147_Create Program and Session"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
